# Generated by Django 4.2 on 2023-04-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todouser',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
